; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.38"

; Modules
projects[ctools][version] = "1.6"
projects[devel][version] = "1.5"
projects[elysia_cron][version] = "2.1"
projects[entity][version] = "1.6"
projects[features][version] = "2.5"
projects[fontawesome][version] = "2.1"
projects[panels][version] = "3.5"
projects[jquery_update][version] = "2.5"
projects[libraries][version] = "2.2"
projects[module_filter][version] = "2.0"
projects[pace][version] = "1.1"
projects[require_login][version] = "1.2"
projects[search_api][version] = "1.14"
projects[search_api_db][version] = "1.4"
projects[simplehtmldom][version] = "1.12"
projects[strongarm][version] = "2.0"
projects[views][version] = "3.10"

; Themes
projects[adminimal_theme][version] = "1.21"