<?php
/**
 * @file
 * security_samurai_gitapi.module
 */

$gitapipath = drupal_get_path('module', 'security_samurai_gitapi');
define('SECURITY_SAMURAI_GITAPI_PATH', $gitapipath);

/**
 * Implements hook_entity_info
 */
function security_samurai_gitapi_entity_info() {

  $info = array();

  // The gitinfo entity.
  $info['gitinfo'] = array(
    'label' => t('Git info'),
    'base table' => 'securitysamurai_gitinfo',
    'entity keys' => array(
      'id' => 'id',
      'label' => 'name',
    ),
    'uri callback' => 'entity_class_uri',
    'entity class' => 'Entity',
    'controller class' => 'GitInfoEntityController',
    'module' => 'security_samurai_gitapi',
    // Default views support.
    'views controller class' => 'EntityDefaultViewsController',
  );

  return $info;
}

/**
 * Extends the EntityAPIController class for the 'site' entity type
 *
 * @method object save()
 * @method object buildContent()
 */
class GitInfoEntityController extends EntityAPIController {
  /**
   * Override the default save function to 
   */
  public function save($entity, DatabaseTransaction $transaction = NULL) {

    if (isset($entity->is_new)) {
      $entity->created_at = REQUEST_TIME;
    }
    $entity->updated_at = REQUEST_TIME;
    return parent::save($entity, $transaction);
  }

  public function buildContent($entity, $view_mode = 'full', $langcode = NULL, $content = array()) {

    $build = parent::buildContent($entity, $view_mode, $langcode, $content);
    return $build;
  }
}

/**
 * Implements hook_load
 *
 * Menu autoloader for site/%site
 */
function gitinfo_load($id) {

  $site = entity_load('gitinfo', array($id));
  return array_pop($site);
}

/**
 * Implements hook_menu
 */
function security_samurai_gitapi_menu() {

  $items = array();

  // The GitAPI configuration page.
  $items['admin/config/development/gitapi'] = array(
    'title' => 'Git API configuration',
    'description' => 'Configure accounts for connecting private repositories',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('security_samurai_gitapi_admin_config_form'),
    'access arguments' => array('administer samurai gitapi'),
    'file' => 'security_samurai_gitapi.admin.inc',
  );

  // Return menu items
  return $items;
}

/**
 * Implements hook_permission()
 */
function security_samurai_gitapi_permission() {

  return array(
    'administer samurai gitapi' => array(
      'title' => t('Administer security samurai GitAPI'),
      'description' => t('Perform administration tasks for security samurai GitAPI.'),
    ),
  );
}

/**
 * Implements hook_form_alter
 */
function security_samurai_gitapi_form_alter(&$form) {
  
  // Override the client form and add in some extra configuration options.
  if ($form['#form_id'] == 'client_site_form') {
    $gitapi_form = array();

    $gitapi_form['security_samurai_gitapi_fieldset'] = array(
      '#type' => 'fieldset',
      '#title' => t('Git configuration'),
      '#description' => t('Set up git branches, clone URLs and tagging per client here.'),
      '#collapsed' => TRUE,
    );
    $gitapi_form['security_samurai_gitapi_fieldset']['security_samurai_gitapi_service'] = array(
      '#type' => 'select',
      '#title' => t('Service'),
      '#description' => t('The Git service to use.'),
      '#options' => array(
        1 => t('GitHub'),
        2 => t('BitBucket'),
        3 => t('Codebase'),
      ),
    );
    $gitapi_form['security_samurai_gitapi_fieldset']['security_samurai_gitapi_clone_url'] = array(
      '#type' => 'textfield',
      '#title' => t('Clone URL'),
      '#description' => t('The Git URL to the repo containing the site.'),
    );
    $gitapi_form['security_samurai_gitapi_fieldset']['security_samurai_gitapi_branch_fieldset'] = array(
      '#type' => 'fieldset',
      '#title' => t('Git workflow'),
      '#description' => t('The workflow you define here can be custom to each site. The steps are followed top to bottom.'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#attributes' => array(
        'class' => array('flatten'),
      ),
    );
    $gitapi_form['security_samurai_gitapi_fieldset']['security_samurai_gitapi_branch_fieldset']['security_samurai_gitapi_model'] = array(
      '#type' => 'select',
      '#title' => t('Add step'),
      '#options' => array(
        0 => '- Add a step to the Git workflow -',
        1 => 'Create a new Samurai branch from an existing branch',
        2 => 'Merge an existing branch in to an existing branch',
        3 => 'Merge the Samurai branch in to an existing branch',
        4 => 'Run security updates and tests',
        5 => 'Delete the samurai branch',
        6 => 'Commit changes to the Samurai branch',
        7 => 'Commit changes to an existing branch',
      ),
      '#ajax' => array(
        'callback' => 'security_samurai_git_branch_model_callback',
        'method' => 'append',
        'wrapper' => 'gitapi_wrapper',
        'effect' => 'slide',
      ),
    );
    $gitapi_form['security_samurai_gitapi_fieldset']['security_samurai_gitapi_branch_fieldset']['security_samurai_add_more'] = array(
      '#type' => 'markup',
      '#markup' => '<div id="gitapi_wrapper"></div>',
    );
    // $gitapi_form['securtity_samurai_gitapi_fieldset']['security_samurai_gitapi_branch_fieldset']['security_samurai_gitapi_']
    // From here the options will be:
    // - User selects Git flow
    // -- Branch to create a feature branch off of.
    // -- Branch to merge that feature branch to after tests pass.
    // - User selects standard
    // -- User selects dev branch
    // -- User selects stage branch
    // -- User selects prod branch

    $gitapi_form['gitapi_workflow_steps'] = array();

    $form = array_merge($form, $gitapi_form);
  }
}

/**
 * Ajax callback for alterations to the client_site_form.
 */
function security_samurai_git_branch_model_callback($form, $form_state) {

  $gitapi_model = $form_state['values']['security_samurai_gitapi_model'];
  $clone_url = $form_state['values']['security_samurai_gitapi_clone_url'];
  $service = $form_state['values']['security_samurai_gitapi_service'];

  // Needs a way of counting the steps so they displayed to the user
  // once the way of counting steps is done - replace $form['step_count']

  $form = array();

  switch ($gitapi_model) {
    case 1:
      // Create a new samurai branch from an existing branch.
      $form['security_samurai_gitapi_fieldset']['security_samurai_gitapi_branch_fieldset']['gitapi_step_title'] = array(
        '#type' => 'markup',
        '#markup' => '<b>' . t('CREATE A NEW SAMURAI BRANCH FROM AN EXISTING BRANCH') . '</b>',
      );
      $form['security_samurai_gitapi_fieldset']['security_samurai_gitapi_branch_fieldset']['gitapi_step_' . $form['step_count'] . '_option_' . $gitapi_model . '_phase_1'] = array(
        '#type' => 'select',
        '#description' => t('Create a new Samurai branch from an existing branch.'),
        '#options' => array(
          1 => 'dev',
          2 => 'stage',
        ),
      );
      break;  
    case 2:
      // Merge an existing branch in to an existing branch.
      $form['security_samurai_gitapi_fieldset']['security_samurai_gitapi_branch_fieldset']['gitapi_step_title'] = array(
        '#type' => 'markup',
        '#markup' => '<b>' . t('MERGE AN EXISTING BRANCH IN TO AN EXISTING BRANCH') . '</b>',
      );
      $form['security_samurai_gitapi_fieldset']['security_samurai_gitapi_branch_fieldset']['gitapi_step_' . $form['step_count'] . '_option_' . $gitapi_model . '_phase_1'] = array(
        '#type' => 'select',
        '#description' => t('Existing branch to merge in to another existing branch.'),
        '#options' => array(
          1 => 'dev',
          2 => 'stage',
        ),
      );
      $form['security_samurai_gitapi_fieldset']['security_samurai_gitapi_branch_fieldset']['gitapi_step_' . $form['step_count'] . '_option_' . $gitapi_model . '_phase_2'] = array(
        '#type' => 'select',
        '#description' => t('Existing branch that will be merged in to.'),
        '#options' => array(
          1 => 'dev',
          2 => 'stage',
        ),
      );
      break;
    case 3:
      // Merge the samurai branch in to an existing branch.
      $form['security_samurai_gitapi_fieldset']['security_samurai_gitapi_branch_fieldset']['gitapi_step_title'] = array(
        '#type' => 'markup',
        '#markup' => '<b>' . t('MERGE THE SAMURAI BRANCH IN TO AN EXISTING BRANCH') . '</b>',
      );
      $form['security_samurai_gitapi_fieldset']['security_samurai_gitapi_branch_fieldset']['gitapi_step_' . $form['step_count'] . '_option_' . $gitapi_model . '_phase_1'] = array(
        '#type' => 'select',
        '#description' => t('Existing branch that will be merged in to.'),
        '#options' => array(
          1 => 'dev',
          2 => 'stage',
        ),
      );
      break;
    case 4:
      // Run the security updates and tests.
      $form['security_samurai_gitapi_fieldset']['security_samurai_gitapi_branch_fieldset']['gitapi_step_title'] = array(
        '#type' => 'markup',
        '#markup' => '<b>' . t('RUN THE SECURITY UPDATES AND TESTS') . '</b>',
      );
      $form['security_samurai_gitapi_fieldset']['security_samurai_gitapi_branch_fieldset']['gitapi_step_' . $form['step_count'] . '_option_' . $gitapi_model . '_phase_1'] = array(
          '#type' => 'hidden',
          '#value' => 'run',
      );
      break;
    case 5:
      // Delete the samurai branch
      $form['security_samurai_gitapi_fieldset']['security_samurai_gitapi_branch_fieldset']['gitapi_step_title'] = array(
        '#type' => 'markup',
        '#markup' => '<b>' . t('DELETE THE SAMURAI BRANCH') . '</b>',
      );
      $form['security_samurai_gitapi_fieldset']['security_samurai_gitapi_branch_fieldset']['gitapi_step_' . $form['step_count'] . '_option_' . $gitapi_model . '_phase_1'] = array(
        '#type' => 'hidden',
        '#value' => 'delete',
      );
      break;
    case 6:
      // Commit changes to the Samurai branch
      $form['security_samurai_gitapi_fieldset']['security_samurai_gitapi_branch_fieldset']['gitapi_step_title'] = array(
        '#type' => 'markup',
        '#markup' => '<b>' . t('COMMIT CHANGES TO THE SAMURAI BRANCH') . '</b>'
      );
      $form['security_samurai_gitapi_fieldset']['security_samurai_gitapi_branch_fieldset']['gitapi_step_' . $form['step_count'] . '_option_' . $gitapi_model . '_phase_1'] = array(
        '#type' => 'hidden',
        '#value' => 'commit',
      );
      break;
    case 7:
      // Commit changes to an existing branch
      $form['security_samurai_gitapi_fieldset']['security_samurai_gitapi_branch_fieldset']['gitapi_step_title'] = array(
        '#type' => 'markup',
        '#markup' => '<b>' . t('COMMIT CHANGES TO AN EXISTING BRANCH') . '</b>',
      );
      $form['security_samurai_gitapi_fieldset']['security_samurai_gitapi_branch_fieldset']['gitapi_step_' . $form['step_count'] . '_option_' . $gitapi_model . '_phase_1'] = array(
        '#type' => 'select',
        '#description' => t('Existing branch to commit the changes to'),
        '#options' => array(
          1 => 'dev',
          2 => 'stage',
        ),
      );
      break;
  }

  return $form;
}