<?php
/**
 * @file
 * security_samurai_gitapi.module
 */

$gitapipath = drupal_get_path('module', 'security_samurai_gitapi');
define('SECURITY_SAMURAI_GITAPI_PATH', $gitapipath);

/**
 * Implements hook_menu
 */
function security_samurai_gitapi_menu() {

  $items = array();

  // The GitAPI configuration page.
  $items['admin/config/development/gitapi'] = array(
    'title' => 'Git API configuration',
    'description' => 'Configure accounts for connecting private repositories',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('security_samurai_gitapi_admin_config_form'),
    'access arguments' => array('administer samurai gitapi'),
    'file' => 'security_samurai_gitapi.admin.inc',
  );

  // Return menu items
  return $items;
}

/**
 * Implements hook_permission()
 */
function security_samurai_gitapi_permission() {

  return array(
    'administer samurai gitapi' => array(
      'title' => t('Administer security samurai GitAPI'),
      'description' => t('Perform administration tasks for security samurai GitAPI.'),
    ),
  );
}

/**
 * Implements hook_form_alter
 */
function security_samurai_gitapi_form_alter(&$form) {
  
  // Override the client form and add in some extra configuration options.
  if ($form['#form_id'] == 'client_site_form') {
    $gitapi_form = array();

    $gitapi_form['security_samurai_gitapi_fieldset'] = array(
      '#type' => 'fieldset',
      '#title' => t('Git configuration'),
      '#description' => t('Set up git branches, clone URLs and tagging per client here.'),
    );

    $gitapi_form['security_samurai_gitapi_fieldset']['security_samurai_gitapi_clone_url'] = array(
      '#type' => 'textfield',
      '#title' => t('Clone URL'),
      '#description' => t('The Git URL to the repo containing the site.'),
    );

    $gitapi_form['security_samurai_gitapi_fieldset']['security_samurai_gitapi_branch_fieldset'] = array(
      '#type' => 'fieldset',
      '#title' => t('Branching options'),
      '#description' => t('Configure which branches to use and where to push'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );
     
    // Maybe should be a selectbox to choose from the existing git branches.
    $gitapi_form['security_samurai_gitapi_fieldset']['security_samurai_gitapi_branch_fieldset']['security_samurai_gitapi_branch_off'] = array(
      '#type' => 'textfield',
      '#title' => t('Branch to create a new branch from'),
      '#description' => t('Git branch to checkout a new branch from for the security updates'),
    );

    $gitapi_form['security_samurai_gitapi_fieldset']['security_samurai_gitapi_branch_fieldset']['security_samurai_gitapi_branch_'] = array(
      '#type' => 'textfield',
      '#title' => t('Branch to push to'),
      '#description' => t('After performing a successful update, push changes to a branch. Will default to [currentdate]-samurai-security.'),
    );

    $form = array_merge($form, $gitapi_form);
  }
}
