<?php
/**
 * @file
 * security_samurai_aliases.module
 */

/*
  Retrieving update data in a readable format:
    drush ups --format="json" - depends on drush 6.x +
*/

/**
 * Implements hook_cron()
 */
function security_samurai_aliases_cron() {

  // On run, rebuild the site alias variable

  // - Retrieve the last run timestamp
  // - Retrieve the run interval - default to 12 hours
  $last_run = variable_get('security_samurai_aliases_last_run', 0);
  $run_interval = variable_get('security_samurai_aliases_interval', 43200);

  if (REQUEST_TIME <= ($last_run + $run_interval) || $last_run == 0) {

    // - Initalise new SamuraiAliases class
    // - Retrieve the array of aliases
    $aliases = new SamuraiAliases();
    $return = $aliases->get_all_aliases();

    // Set the Drupal variables
    variable_set('security_samurai_aliases', $return);
    variable_set('security_samurai_aliases_last_run', REQUEST_TIME);
  }
}

/**
 * Check if an alias is present on the server
 * Returns TRUE/FALSE
 *
 * @param string $site_alias The name of the site alias
 */
function security_samurai_aliases_alias_exists($site_alias) {

  // Not yet implemented
}

/**
 * Sync a database with an existing container
 *
 * @param string $site_alias The name of the site alias
 * @param int $container_row_id The row ID of the container
 */
function security_samurai_aliases_sync_database($site_alias, $container_row_id) {

  // Not yet implemented

  // - Dump the database
  // - Sync up to the docker container
  // - Delete the database dump
}
