<?php
/**
 * @file
 * security_samurai_docker.module 
 */

/**
 * Implements hook_menu
 */
function security_samurai_docker_menu() {
  $items = array();

  // Docker administration configuration page.
  $items['admin/config/development/docker'] = array(
    'title' => t('Docker configuration'),
    'description' => 'Configuration settings related to docker container setups.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('security_samurai_docker_admin_config_form'),
    'access arguments' => array('administer samurai docker'),
    'file' => 'security_samurai_docker.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission()
 */
function security_samurai_docker_permission() {
  return array(
    'administer samurai docker' => array(
      'title' => t('Administer security samurai docker'),
      'description' => t('Perform administration tasks for security samurai docker.'),
    ),
  );
}

/**
 * Implements hook_form_alter()
 */
function security_samurai_docker_form_alter(&$form) {

  // Override the client form and add in some extra configuration options.
  if ($form['#form_id'] == 'client_site_form') {

    $form['docker_site_form_fieldset'] = array(
      '#type' => 'fieldset',
      '#title' => t('Docker configuration'),
      '#description' => t('Docker is used for creating test environments when applying the security updates. The below configuration options are custom to this client.'),
    );

    $form['docker_site_form_fieldset']['docker_site_form_makefile_check'] = array(
      '#type' => 'checkbox',
      '#title' => t('Will Docker need to run a make file?'),
      '#description' => t('Will Docker need to run a make file to download code/modules/assets?'),
    );

    $form['docker_site_form_fieldset']['docker_site_form_makefile_location'] = array(
      '#type' => 'textfield',
      '#title' => t('The location and name of the make file in the Git repository'),
      '#description' => t('Example: samurai/samurai.make'),
    );

    $form['#submit'][] = 'security_samurai_docker_client_site_form_submit';
  }
}

/**
 * Implements form_submit()
 * The form submit handler for security_samurai_docker form alterations.
 */
function security_samurai_docker_client_site_form_submit($form_id, &$form_state) {

  // Get the client_site ID
}